Add git diff check

diff --git a/.github/workflows/auto-create-pr.yml b/.github/workflows/auto-create-pr.yml
--- a/.github/workflows/auto-create-pr.yml
+++ b/.github/workflows/auto-create-pr.yml
@@ -25,8 +25,10 @@ env:
   GITHUB_TOKEN: ${{ secrets.gh_token }}
 
 jobs:
+  # Job to check for existing PR with the same branches
+  # and if there are differences between the branches
   check-for-existing-pr:
-    name: Check for existing PR
+    name: Check for existing pull request
 
     runs-on: ubuntu-latest
 
@@ -36,26 +38,33 @@ jobs:
 
     outputs:
       prs: ${{ steps.check.outputs.prs }}
+      files_changed: ${{ steps.check.outputs.files_changed }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
-      # Output JSON to output called prs
+      # Output PR list JSON to prs and diff status code to files_changed
       - id: check
         name: Check for existing PRs
         run: | 
-          echo ${{ inputs.base_branch }}
-          echo ${{ inputs.head_branch }}
           prs_json=$(gh pr list --state open \
             --base ${{ inputs.base_branch }} \
             --head ${{ inputs.head_branch }} \
             --json url)
           echo $prs_json
           echo "::set-output name=prs::$prs_json"
+          
+          git fetch
+          # Use || to prevent script from exiting on non-zero exit code
+          git diff remotes/origin/${{ inputs.base_branch }}..remotes/origin/${{ inputs.head_branch }} --quiet || diff_code=$?
+          if [ $diff_code != '1' ] && [ $diff_code != '0' ]; then exit $diff_code; fi
+          echo "git diff code: $diff_code"
+          echo "::set-output name=files_changed::$diff_code"
 
+  # Job to create a pull request
   create-pr:
-    name: Create release PR
+    name: Create pull request
 
     runs-on: ubuntu-latest
 
@@ -66,8 +75,8 @@ jobs:
 
     needs: check-for-existing-pr
 
-    # Only run if no existing release PRs exist
-    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] == null }}
+    # Only run if no existing release PRs exist and there is a difference between the branches (no run for merge commits)
+    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] == null && needs.check-for-existing-pr.outputs.files_changed == '1' }}
 
     steps:
       - name: Checkout
@@ -90,17 +99,3 @@ jobs:
             --head ${{ inputs.head_branch }} \
             --json number | jq '.[0].number')
           gh pr edit $pr_num --add-label release
-
-  pr-exists:
-    name: Release PR already exists
-
-    runs-on: ubuntu-latest
-
-    needs: check-for-existing-pr
-
-    # Only run if no existing release PRs exist
-    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] != null }}
-
-    steps:
-      - name: Release PR already exists
-        run: echo ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0].url }}
